services:
  change-volume-owner:
    image: odoo:14.0
    user: root
    volumes:
      - ./odoo-data:/var/lib/odoo
    command: chown -R odoo:odoo /var/lib/odoo

  odoo:
    container_name: odoo
    image: odoo:14.0
    restart: always
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo.rule=Host(`odoo.ayou20.iutinfo.fr`)"
      - "traefik.http.services.odoo.loadbalancer.server.port="
    depends_on:
      change-volume-owner:
        condition: service_completed_successfully
    networks:
       - net-traefik

networks:
  net-traefik:
     external: true
secrets:
  postgresql_password:
     file: mdp_file
